version: "3.9"

services:
  redis:
    image: redis:7.2-alpine
    container_name: game_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "900", "1", "--appendonly", "yes"]

volumes:
  redis_data:
    name: game_redis_data
